// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: api/v1/hello.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserViewEnum int32

const (
	// 无视图，占位不可使用
	UserViewEnum_NONE_VIEW UserViewEnum = 0
	// 用户基础信息的视图，视图返回信息见BASEINFO，如果请求包含此视图但获取失败则报错；
	UserViewEnum_BASE_INFO_VIEW UserViewEnum = 1
)

// Enum value maps for UserViewEnum.
var (
	UserViewEnum_name = map[int32]string{
		0: "NONE_VIEW",
		1: "BASE_INFO_VIEW",
	}
	UserViewEnum_value = map[string]int32{
		"NONE_VIEW":      0,
		"BASE_INFO_VIEW": 1,
	}
)

func (x UserViewEnum) Enum() *UserViewEnum {
	p := new(UserViewEnum)
	*p = x
	return p
}

func (x UserViewEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserViewEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_hello_proto_enumTypes[0].Descriptor()
}

func (UserViewEnum) Type() protoreflect.EnumType {
	return &file_api_v1_hello_proto_enumTypes[0]
}

func (x UserViewEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserViewEnum.Descriptor instead.
func (UserViewEnum) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_hello_proto_rawDescGZIP(), []int{0}
}

// The request message containing the user's name.
type HelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_hello_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_hello_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_hello_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetViewReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Views []*UserViewItem `protobuf:"bytes,2,rep,name=views,proto3" json:"views,omitempty"`
}

func (x *GetViewReq) Reset() {
	*x = GetViewReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_hello_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetViewReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetViewReq) ProtoMessage() {}

func (x *GetViewReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_hello_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetViewReq.ProtoReflect.Descriptor instead.
func (*GetViewReq) Descriptor() ([]byte, []int) {
	return file_api_v1_hello_proto_rawDescGZIP(), []int{1}
}

func (x *GetViewReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetViewReq) GetViews() []*UserViewItem {
	if x != nil {
		return x.Views
	}
	return nil
}

type UserViewItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 视图枚举
	View UserViewEnum `protobuf:"varint,1,opt,name=view,proto3,enum=grpcdemo.v1.UserViewEnum" json:"view,omitempty"`
	// 如果某种view获取信息时需要有额外信息，那么view提供方定义好对应的option要求调用方传入，例如fans_medal_option 或user_reserve_option
	Options *anypb.Any `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *UserViewItem) Reset() {
	*x = UserViewItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_hello_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserViewItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserViewItem) ProtoMessage() {}

func (x *UserViewItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_hello_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserViewItem.ProtoReflect.Descriptor instead.
func (*UserViewItem) Descriptor() ([]byte, []int) {
	return file_api_v1_hello_proto_rawDescGZIP(), []int{2}
}

func (x *UserViewItem) GetView() UserViewEnum {
	if x != nil {
		return x.View
	}
	return UserViewEnum_NONE_VIEW
}

func (x *UserViewItem) GetOptions() *anypb.Any {
	if x != nil {
		return x.Options
	}
	return nil
}

type FansMedalOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 某个up主的粉丝勋章，即获取mids是否拥有该up_mid的粉丝勋章，对应视图：REPLY_FANS_MEDAL_VIEW 和  REPLY_FANS_MEDAL_V2_VIEW
	UpMid int64 `protobuf:"varint,1,opt,name=up_mid,json=upMid,proto3" json:"up_mid,omitempty"`
}

func (x *FansMedalOptions) Reset() {
	*x = FansMedalOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_hello_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FansMedalOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FansMedalOptions) ProtoMessage() {}

func (x *FansMedalOptions) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_hello_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FansMedalOptions.ProtoReflect.Descriptor instead.
func (*FansMedalOptions) Descriptor() ([]byte, []int) {
	return file_api_v1_hello_proto_rawDescGZIP(), []int{3}
}

func (x *FansMedalOptions) GetUpMid() int64 {
	if x != nil {
		return x.UpMid
	}
	return 0
}

// The response message containing the greetings
type HelloReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Num     int64  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_hello_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_hello_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_api_v1_hello_proto_rawDescGZIP(), []int{4}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HelloReply) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type GetIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetIdReq) Reset() {
	*x = GetIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_hello_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdReq) ProtoMessage() {}

func (x *GetIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_hello_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdReq.ProtoReflect.Descriptor instead.
func (*GetIdReq) Descriptor() ([]byte, []int) {
	return file_api_v1_hello_proto_rawDescGZIP(), []int{5}
}

type GetIDsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *GetIDsResp) Reset() {
	*x = GetIDsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_hello_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIDsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIDsResp) ProtoMessage() {}

func (x *GetIDsResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_hello_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIDsResp.ProtoReflect.Descriptor instead.
func (*GetIDsResp) Descriptor() ([]byte, []int) {
	return file_api_v1_hello_proto_rawDescGZIP(), []int{6}
}

func (x *GetIDsResp) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetViewResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Num  int64  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *GetViewResp) Reset() {
	*x = GetViewResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_hello_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetViewResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetViewResp) ProtoMessage() {}

func (x *GetViewResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_hello_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetViewResp.ProtoReflect.Descriptor instead.
func (*GetViewResp) Descriptor() ([]byte, []int) {
	return file_api_v1_hello_proto_rawDescGZIP(), []int{7}
}

func (x *GetViewResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetViewResp) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

var File_api_v1_hello_proto protoreflect.FileDescriptor

var file_api_v1_hello_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x76,
	0x31, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x22, 0x0a, 0x0c,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x51, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x56, 0x69, 0x65, 0x77, 0x52, 0x65, 0x71, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x05, 0x76, 0x69, 0x65, 0x77, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x56, 0x69, 0x65, 0x77, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x76, 0x69,
	0x65, 0x77, 0x73, 0x22, 0x6d, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x56, 0x69, 0x65, 0x77, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x2d, 0x0a, 0x04, 0x76, 0x69, 0x65, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x56, 0x69, 0x65, 0x77, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x04, 0x76, 0x69,
	0x65, 0x77, 0x12, 0x2e, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x22, 0x29, 0x0a, 0x10, 0x46, 0x61, 0x6e, 0x73, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x75, 0x70, 0x5f, 0x6d, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x75, 0x70, 0x4d, 0x69, 0x64, 0x22, 0x38, 0x0a,
	0x0a, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x0a, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x22, 0x1e, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x49, 0x44, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03,
	0x69, 0x64, 0x73, 0x22, 0x33, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x56, 0x69, 0x65, 0x77, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x2a, 0x31, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72,
	0x56, 0x69, 0x65, 0x77, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x4e, 0x45,
	0x5f, 0x56, 0x49, 0x45, 0x57, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x42, 0x41, 0x53, 0x45, 0x5f,
	0x49, 0x4e, 0x46, 0x4f, 0x5f, 0x56, 0x49, 0x45, 0x57, 0x10, 0x01, 0x32, 0xc4, 0x01, 0x0a, 0x05,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x40, 0x0a, 0x08, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x12, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x76, 0x31, 0x2e,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x05, 0x47, 0x65, 0x74, 0x49, 0x44,
	0x12, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65,
	0x6d, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x44, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x12, 0x3e, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x56, 0x69, 0x65, 0x77, 0x12, 0x17, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x56,
	0x69, 0x65, 0x77, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d,
	0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x69, 0x65, 0x77, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_hello_proto_rawDescOnce sync.Once
	file_api_v1_hello_proto_rawDescData = file_api_v1_hello_proto_rawDesc
)

func file_api_v1_hello_proto_rawDescGZIP() []byte {
	file_api_v1_hello_proto_rawDescOnce.Do(func() {
		file_api_v1_hello_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_hello_proto_rawDescData)
	})
	return file_api_v1_hello_proto_rawDescData
}

var file_api_v1_hello_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_v1_hello_proto_goTypes = []interface{}{
	(UserViewEnum)(0),        // 0: grpcdemo.v1.UserViewEnum
	(*HelloRequest)(nil),     // 1: grpcdemo.v1.HelloRequest
	(*GetViewReq)(nil),       // 2: grpcdemo.v1.GetViewReq
	(*UserViewItem)(nil),     // 3: grpcdemo.v1.UserViewItem
	(*FansMedalOptions)(nil), // 4: grpcdemo.v1.FansMedalOptions
	(*HelloReply)(nil),       // 5: grpcdemo.v1.HelloReply
	(*GetIdReq)(nil),         // 6: grpcdemo.v1.GetIdReq
	(*GetIDsResp)(nil),       // 7: grpcdemo.v1.GetIDsResp
	(*GetViewResp)(nil),      // 8: grpcdemo.v1.GetViewResp
	(*anypb.Any)(nil),        // 9: google.protobuf.Any
}
var file_api_v1_hello_proto_depIdxs = []int32{
	3, // 0: grpcdemo.v1.GetViewReq.views:type_name -> grpcdemo.v1.UserViewItem
	0, // 1: grpcdemo.v1.UserViewItem.view:type_name -> grpcdemo.v1.UserViewEnum
	9, // 2: grpcdemo.v1.UserViewItem.options:type_name -> google.protobuf.Any
	1, // 3: grpcdemo.v1.Hello.SayHello:input_type -> grpcdemo.v1.HelloRequest
	6, // 4: grpcdemo.v1.Hello.GetID:input_type -> grpcdemo.v1.GetIdReq
	2, // 5: grpcdemo.v1.Hello.GetView:input_type -> grpcdemo.v1.GetViewReq
	5, // 6: grpcdemo.v1.Hello.SayHello:output_type -> grpcdemo.v1.HelloReply
	7, // 7: grpcdemo.v1.Hello.GetID:output_type -> grpcdemo.v1.GetIDsResp
	8, // 8: grpcdemo.v1.Hello.GetView:output_type -> grpcdemo.v1.GetViewResp
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_v1_hello_proto_init() }
func file_api_v1_hello_proto_init() {
	if File_api_v1_hello_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_hello_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_hello_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetViewReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_hello_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserViewItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_hello_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FansMedalOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_hello_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_hello_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_hello_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIDsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_hello_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetViewResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_hello_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_hello_proto_goTypes,
		DependencyIndexes: file_api_v1_hello_proto_depIdxs,
		EnumInfos:         file_api_v1_hello_proto_enumTypes,
		MessageInfos:      file_api_v1_hello_proto_msgTypes,
	}.Build()
	File_api_v1_hello_proto = out.File
	file_api_v1_hello_proto_rawDesc = nil
	file_api_v1_hello_proto_goTypes = nil
	file_api_v1_hello_proto_depIdxs = nil
}
