// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/v1/hello.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserViewEnum int32

const (
	// 无视图，占位不可使用
	UserViewEnum_NONE_VIEW UserViewEnum = 0
	// 用户基础信息的视图，视图返回信息见BASEINFO，如果请求包含此视图但获取失败则报错；
	UserViewEnum_BASE_INFO_VIEW UserViewEnum = 1
)

var UserViewEnum_name = map[int32]string{
	0: "NONE_VIEW",
	1: "BASE_INFO_VIEW",
}

var UserViewEnum_value = map[string]int32{
	"NONE_VIEW":      0,
	"BASE_INFO_VIEW": 1,
}

func (x UserViewEnum) String() string {
	return proto.EnumName(UserViewEnum_name, int32(x))
}

func (UserViewEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5fa05ff323b51367, []int{0}
}

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fa05ff323b51367, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetViewReq struct {
	Name                 string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Views                []*UserViewItem `protobuf:"bytes,2,rep,name=views,proto3" json:"views,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetViewReq) Reset()         { *m = GetViewReq{} }
func (m *GetViewReq) String() string { return proto.CompactTextString(m) }
func (*GetViewReq) ProtoMessage()    {}
func (*GetViewReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fa05ff323b51367, []int{1}
}

func (m *GetViewReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetViewReq.Unmarshal(m, b)
}
func (m *GetViewReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetViewReq.Marshal(b, m, deterministic)
}
func (m *GetViewReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetViewReq.Merge(m, src)
}
func (m *GetViewReq) XXX_Size() int {
	return xxx_messageInfo_GetViewReq.Size(m)
}
func (m *GetViewReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetViewReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetViewReq proto.InternalMessageInfo

func (m *GetViewReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetViewReq) GetViews() []*UserViewItem {
	if m != nil {
		return m.Views
	}
	return nil
}

type UserViewItem struct {
	// 视图枚举
	View UserViewEnum `protobuf:"varint,1,opt,name=view,proto3,enum=grpcdemo.v1.UserViewEnum" json:"view,omitempty"`
	// 如果某种view获取信息时需要有额外信息，那么view提供方定义好对应的option要求调用方传入，例如fans_medal_option 或user_reserve_option
	Options              *any.Any `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserViewItem) Reset()         { *m = UserViewItem{} }
func (m *UserViewItem) String() string { return proto.CompactTextString(m) }
func (*UserViewItem) ProtoMessage()    {}
func (*UserViewItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fa05ff323b51367, []int{2}
}

func (m *UserViewItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserViewItem.Unmarshal(m, b)
}
func (m *UserViewItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserViewItem.Marshal(b, m, deterministic)
}
func (m *UserViewItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserViewItem.Merge(m, src)
}
func (m *UserViewItem) XXX_Size() int {
	return xxx_messageInfo_UserViewItem.Size(m)
}
func (m *UserViewItem) XXX_DiscardUnknown() {
	xxx_messageInfo_UserViewItem.DiscardUnknown(m)
}

var xxx_messageInfo_UserViewItem proto.InternalMessageInfo

func (m *UserViewItem) GetView() UserViewEnum {
	if m != nil {
		return m.View
	}
	return UserViewEnum_NONE_VIEW
}

func (m *UserViewItem) GetOptions() *any.Any {
	if m != nil {
		return m.Options
	}
	return nil
}

type FansMedalOptions struct {
	// 某个up主的粉丝勋章，即获取mids是否拥有该up_mid的粉丝勋章，对应视图：REPLY_FANS_MEDAL_VIEW 和  REPLY_FANS_MEDAL_V2_VIEW
	UpMid                int64    `protobuf:"varint,1,opt,name=up_mid,json=upMid,proto3" json:"up_mid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FansMedalOptions) Reset()         { *m = FansMedalOptions{} }
func (m *FansMedalOptions) String() string { return proto.CompactTextString(m) }
func (*FansMedalOptions) ProtoMessage()    {}
func (*FansMedalOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fa05ff323b51367, []int{3}
}

func (m *FansMedalOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FansMedalOptions.Unmarshal(m, b)
}
func (m *FansMedalOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FansMedalOptions.Marshal(b, m, deterministic)
}
func (m *FansMedalOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FansMedalOptions.Merge(m, src)
}
func (m *FansMedalOptions) XXX_Size() int {
	return xxx_messageInfo_FansMedalOptions.Size(m)
}
func (m *FansMedalOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_FansMedalOptions.DiscardUnknown(m)
}

var xxx_messageInfo_FansMedalOptions proto.InternalMessageInfo

func (m *FansMedalOptions) GetUpMid() int64 {
	if m != nil {
		return m.UpMid
	}
	return 0
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Num                  int64    `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fa05ff323b51367, []int{4}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *HelloReply) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

type GetIdReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIdReq) Reset()         { *m = GetIdReq{} }
func (m *GetIdReq) String() string { return proto.CompactTextString(m) }
func (*GetIdReq) ProtoMessage()    {}
func (*GetIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fa05ff323b51367, []int{5}
}

func (m *GetIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIdReq.Unmarshal(m, b)
}
func (m *GetIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIdReq.Marshal(b, m, deterministic)
}
func (m *GetIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIdReq.Merge(m, src)
}
func (m *GetIdReq) XXX_Size() int {
	return xxx_messageInfo_GetIdReq.Size(m)
}
func (m *GetIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetIdReq proto.InternalMessageInfo

type GetIDsResp struct {
	Ids                  []int64  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIDsResp) Reset()         { *m = GetIDsResp{} }
func (m *GetIDsResp) String() string { return proto.CompactTextString(m) }
func (*GetIDsResp) ProtoMessage()    {}
func (*GetIDsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fa05ff323b51367, []int{6}
}

func (m *GetIDsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIDsResp.Unmarshal(m, b)
}
func (m *GetIDsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIDsResp.Marshal(b, m, deterministic)
}
func (m *GetIDsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIDsResp.Merge(m, src)
}
func (m *GetIDsResp) XXX_Size() int {
	return xxx_messageInfo_GetIDsResp.Size(m)
}
func (m *GetIDsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIDsResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetIDsResp proto.InternalMessageInfo

func (m *GetIDsResp) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetViewResp struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Num                  int64    `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetViewResp) Reset()         { *m = GetViewResp{} }
func (m *GetViewResp) String() string { return proto.CompactTextString(m) }
func (*GetViewResp) ProtoMessage()    {}
func (*GetViewResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fa05ff323b51367, []int{7}
}

func (m *GetViewResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetViewResp.Unmarshal(m, b)
}
func (m *GetViewResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetViewResp.Marshal(b, m, deterministic)
}
func (m *GetViewResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetViewResp.Merge(m, src)
}
func (m *GetViewResp) XXX_Size() int {
	return xxx_messageInfo_GetViewResp.Size(m)
}
func (m *GetViewResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetViewResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetViewResp proto.InternalMessageInfo

func (m *GetViewResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetViewResp) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

type GetStreamReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStreamReq) Reset()         { *m = GetStreamReq{} }
func (m *GetStreamReq) String() string { return proto.CompactTextString(m) }
func (*GetStreamReq) ProtoMessage()    {}
func (*GetStreamReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fa05ff323b51367, []int{8}
}

func (m *GetStreamReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStreamReq.Unmarshal(m, b)
}
func (m *GetStreamReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStreamReq.Marshal(b, m, deterministic)
}
func (m *GetStreamReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStreamReq.Merge(m, src)
}
func (m *GetStreamReq) XXX_Size() int {
	return xxx_messageInfo_GetStreamReq.Size(m)
}
func (m *GetStreamReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStreamReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetStreamReq proto.InternalMessageInfo

func (m *GetStreamReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetStreamResp struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStreamResp) Reset()         { *m = GetStreamResp{} }
func (m *GetStreamResp) String() string { return proto.CompactTextString(m) }
func (*GetStreamResp) ProtoMessage()    {}
func (*GetStreamResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fa05ff323b51367, []int{9}
}

func (m *GetStreamResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStreamResp.Unmarshal(m, b)
}
func (m *GetStreamResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStreamResp.Marshal(b, m, deterministic)
}
func (m *GetStreamResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStreamResp.Merge(m, src)
}
func (m *GetStreamResp) XXX_Size() int {
	return xxx_messageInfo_GetStreamResp.Size(m)
}
func (m *GetStreamResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStreamResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetStreamResp proto.InternalMessageInfo

func (m *GetStreamResp) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterEnum("grpcdemo.v1.UserViewEnum", UserViewEnum_name, UserViewEnum_value)
	proto.RegisterType((*HelloRequest)(nil), "grpcdemo.v1.HelloRequest")
	proto.RegisterType((*GetViewReq)(nil), "grpcdemo.v1.GetViewReq")
	proto.RegisterType((*UserViewItem)(nil), "grpcdemo.v1.UserViewItem")
	proto.RegisterType((*FansMedalOptions)(nil), "grpcdemo.v1.FansMedalOptions")
	proto.RegisterType((*HelloReply)(nil), "grpcdemo.v1.HelloReply")
	proto.RegisterType((*GetIdReq)(nil), "grpcdemo.v1.GetIdReq")
	proto.RegisterType((*GetIDsResp)(nil), "grpcdemo.v1.GetIDsResp")
	proto.RegisterType((*GetViewResp)(nil), "grpcdemo.v1.GetViewResp")
	proto.RegisterType((*GetStreamReq)(nil), "grpcdemo.v1.GetStreamReq")
	proto.RegisterType((*GetStreamResp)(nil), "grpcdemo.v1.GetStreamResp")
}

func init() { proto.RegisterFile("api/v1/hello.proto", fileDescriptor_5fa05ff323b51367) }

var fileDescriptor_5fa05ff323b51367 = []byte{
	// 471 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x80, 0xe3, 0xa6, 0xf9, 0x9b, 0xa4, 0x55, 0x34, 0xa2, 0x90, 0xfa, 0x80, 0xa2, 0xbd, 0x10,
	0x90, 0xb0, 0x49, 0x7a, 0x81, 0x0b, 0xa2, 0x15, 0x49, 0xf0, 0xa1, 0x89, 0xd8, 0x88, 0x22, 0x71,
	0x89, 0x5c, 0x3c, 0x04, 0x4b, 0xfe, 0xd9, 0x78, 0xed, 0x54, 0x7e, 0x07, 0x1e, 0x1a, 0x79, 0x6d,
	0xb7, 0x6e, 0x9b, 0xdc, 0x76, 0x77, 0xbe, 0xd9, 0xf1, 0x7e, 0x33, 0x06, 0xb4, 0x85, 0x6b, 0xee,
	0xc6, 0xe6, 0x5f, 0xf2, 0xbc, 0xd0, 0x10, 0x51, 0x18, 0x87, 0xd8, 0xdd, 0x44, 0xe2, 0xb7, 0x43,
	0x7e, 0x68, 0xec, 0xc6, 0xfa, 0xf9, 0x26, 0x0c, 0x37, 0x1e, 0x99, 0x2a, 0x74, 0x9b, 0xfc, 0x31,
	0xed, 0x20, 0xcd, 0x39, 0xc6, 0xa0, 0xf7, 0x2d, 0x4b, 0xe3, 0xb4, 0x4d, 0x48, 0xc6, 0x88, 0x70,
	0x1c, 0xd8, 0x3e, 0x0d, 0xb4, 0xa1, 0x36, 0xea, 0x70, 0xb5, 0x66, 0xdf, 0x01, 0xe6, 0x14, 0xdf,
	0xb8, 0x74, 0xc7, 0x69, 0xbb, 0x8f, 0x40, 0x13, 0x1a, 0x3b, 0x97, 0xee, 0xe4, 0xe0, 0x68, 0x58,
	0x1f, 0x75, 0x27, 0xe7, 0x46, 0xa5, 0xba, 0xf1, 0x43, 0x52, 0x94, 0x25, 0x5b, 0x31, 0xf9, 0x3c,
	0xe7, 0x98, 0x0f, 0xbd, 0xea, 0x31, 0xbe, 0x87, 0xe3, 0x2c, 0xa0, 0x2e, 0x3d, 0x3d, 0x90, 0x3f,
	0x0d, 0x12, 0x9f, 0x2b, 0x0c, 0x0d, 0x68, 0x85, 0x22, 0x76, 0xc3, 0x20, 0xab, 0xa8, 0x8d, 0xba,
	0x93, 0x17, 0x46, 0xfe, 0x44, 0xa3, 0x7c, 0xa2, 0x71, 0x19, 0xa4, 0xbc, 0x84, 0xd8, 0x5b, 0xe8,
	0xcf, 0xec, 0x40, 0x5e, 0x93, 0x63, 0x7b, 0xcb, 0xfc, 0x0c, 0xcf, 0xa0, 0x99, 0x88, 0xb5, 0xef,
	0x3a, 0xaa, 0x68, 0x9d, 0x37, 0x12, 0x71, 0xed, 0x3a, 0xec, 0x23, 0x40, 0x21, 0x44, 0x78, 0x29,
	0x0e, 0xa0, 0xe5, 0x93, 0x94, 0xf6, 0xa6, 0x7c, 0x6f, 0xb9, 0xc5, 0x3e, 0xd4, 0x83, 0xc4, 0x57,
	0xe5, 0xeb, 0x3c, 0x5b, 0x32, 0x80, 0xf6, 0x9c, 0x62, 0xcb, 0xe1, 0xb4, 0x65, 0xaf, 0x95, 0x32,
	0xeb, 0xab, 0xe4, 0x24, 0x45, 0xc6, 0xba, 0x8e, 0x1c, 0x68, 0xc3, 0x7a, 0xc6, 0xba, 0x8e, 0x64,
	0x17, 0xd0, 0xbd, 0x57, 0x2a, 0xc5, 0x5e, 0xa7, 0xcf, 0x0b, 0x30, 0xe8, 0xcd, 0x29, 0x5e, 0xc5,
	0x11, 0xd9, 0xfe, 0x81, 0x4e, 0xb0, 0x37, 0x70, 0x52, 0x61, 0xa4, 0xc0, 0x97, 0xd0, 0x8c, 0x48,
	0x26, 0x5e, 0x5c, 0x60, 0xc5, 0xee, 0xdd, 0xf8, 0xa1, 0x03, 0x99, 0x58, 0x3c, 0x81, 0xce, 0x62,
	0xb9, 0x98, 0xae, 0x6f, 0xac, 0xe9, 0xcf, 0x7e, 0x0d, 0x11, 0x4e, 0xaf, 0x2e, 0x57, 0xd3, 0xb5,
	0xb5, 0x98, 0x2d, 0xf3, 0x33, 0x6d, 0xf2, 0xef, 0x08, 0x1a, 0xca, 0x0d, 0x7e, 0x81, 0xf6, 0xca,
	0x4e, 0xf3, 0xf5, 0xe3, 0x66, 0x55, 0x87, 0x49, 0x7f, 0xb5, 0x2f, 0x24, 0xbc, 0x94, 0xd5, 0xf0,
	0x13, 0x34, 0x94, 0x20, 0x3c, 0x7b, 0xc4, 0x94, 0x02, 0x9f, 0xa4, 0x3e, 0xb8, 0x64, 0x35, 0xfc,
	0x0c, 0xad, 0xc2, 0x1d, 0x3e, 0xa3, 0x8a, 0x21, 0xd5, 0x07, 0xfb, 0x03, 0x2a, 0x7f, 0x06, 0x9d,
	0x7b, 0x45, 0x4f, 0xbe, 0xbe, 0xaa, 0x57, 0xd7, 0x0f, 0x85, 0xb2, 0x5b, 0x3e, 0x68, 0x57, 0xed,
	0x5f, 0xcd, 0xfc, 0xc7, 0xbb, 0x6d, 0xaa, 0xa9, 0xbb, 0xf8, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xc5,
	0xb6, 0x29, 0xc9, 0x89, 0x03, 0x00, 0x00,
}
