// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpcclient/protodiff/api/v1/hello.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82937641a6538325, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Num                  int32    `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_82937641a6538325, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *HelloReply) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

type GetIdReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIdReq) Reset()         { *m = GetIdReq{} }
func (m *GetIdReq) String() string { return proto.CompactTextString(m) }
func (*GetIdReq) ProtoMessage()    {}
func (*GetIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_82937641a6538325, []int{2}
}

func (m *GetIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIdReq.Unmarshal(m, b)
}
func (m *GetIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIdReq.Marshal(b, m, deterministic)
}
func (m *GetIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIdReq.Merge(m, src)
}
func (m *GetIdReq) XXX_Size() int {
	return xxx_messageInfo_GetIdReq.Size(m)
}
func (m *GetIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetIdReq proto.InternalMessageInfo

type GetIDsResp struct {
	Ids                  []int64  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIDsResp) Reset()         { *m = GetIDsResp{} }
func (m *GetIDsResp) String() string { return proto.CompactTextString(m) }
func (*GetIDsResp) ProtoMessage()    {}
func (*GetIDsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_82937641a6538325, []int{3}
}

func (m *GetIDsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIDsResp.Unmarshal(m, b)
}
func (m *GetIDsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIDsResp.Marshal(b, m, deterministic)
}
func (m *GetIDsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIDsResp.Merge(m, src)
}
func (m *GetIDsResp) XXX_Size() int {
	return xxx_messageInfo_GetIDsResp.Size(m)
}
func (m *GetIDsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIDsResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetIDsResp proto.InternalMessageInfo

func (m *GetIDsResp) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetStreamReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStreamReq) Reset()         { *m = GetStreamReq{} }
func (m *GetStreamReq) String() string { return proto.CompactTextString(m) }
func (*GetStreamReq) ProtoMessage()    {}
func (*GetStreamReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_82937641a6538325, []int{4}
}

func (m *GetStreamReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStreamReq.Unmarshal(m, b)
}
func (m *GetStreamReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStreamReq.Marshal(b, m, deterministic)
}
func (m *GetStreamReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStreamReq.Merge(m, src)
}
func (m *GetStreamReq) XXX_Size() int {
	return xxx_messageInfo_GetStreamReq.Size(m)
}
func (m *GetStreamReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStreamReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetStreamReq proto.InternalMessageInfo

func (m *GetStreamReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetStreamResp struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStreamResp) Reset()         { *m = GetStreamResp{} }
func (m *GetStreamResp) String() string { return proto.CompactTextString(m) }
func (*GetStreamResp) ProtoMessage()    {}
func (*GetStreamResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_82937641a6538325, []int{5}
}

func (m *GetStreamResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStreamResp.Unmarshal(m, b)
}
func (m *GetStreamResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStreamResp.Marshal(b, m, deterministic)
}
func (m *GetStreamResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStreamResp.Merge(m, src)
}
func (m *GetStreamResp) XXX_Size() int {
	return xxx_messageInfo_GetStreamResp.Size(m)
}
func (m *GetStreamResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStreamResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetStreamResp proto.InternalMessageInfo

func (m *GetStreamResp) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "grpcdemo.v1.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "grpcdemo.v1.HelloReply")
	proto.RegisterType((*GetIdReq)(nil), "grpcdemo.v1.GetIdReq")
	proto.RegisterType((*GetIDsResp)(nil), "grpcdemo.v1.GetIDsResp")
	proto.RegisterType((*GetStreamReq)(nil), "grpcdemo.v1.GetStreamReq")
	proto.RegisterType((*GetStreamResp)(nil), "grpcdemo.v1.GetStreamResp")
}

func init() {
	proto.RegisterFile("grpcclient/protodiff/api/v1/hello.proto", fileDescriptor_82937641a6538325)
}

var fileDescriptor_82937641a6538325 = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x4f, 0x83, 0x30,
	0x14, 0xc6, 0x57, 0x27, 0xc8, 0x9e, 0x9a, 0x98, 0x26, 0x2a, 0x72, 0x30, 0xa4, 0x97, 0x71, 0x02,
	0xa7, 0x17, 0xbd, 0x19, 0x63, 0x9c, 0x5e, 0xbb, 0x9b, 0x37, 0x1c, 0x6f, 0x93, 0xa4, 0x40, 0xa1,
	0x65, 0x09, 0xff, 0xa3, 0x7f, 0x94, 0x29, 0x03, 0xc5, 0x65, 0xde, 0xbe, 0xd7, 0xef, 0xd7, 0xf6,
	0xfb, 0xf2, 0x60, 0xba, 0xae, 0xe4, 0x72, 0x29, 0x52, 0xcc, 0x75, 0x24, 0xab, 0x42, 0x17, 0x49,
	0xba, 0x5a, 0x45, 0xb1, 0x4c, 0xa3, 0xcd, 0x2c, 0xfa, 0x44, 0x21, 0x8a, 0xb0, 0x3d, 0xa6, 0xc7,
	0x06, 0x4c, 0x30, 0x2b, 0xc2, 0xcd, 0x8c, 0x31, 0x38, 0x79, 0x35, 0x1e, 0xc7, 0xb2, 0x46, 0xa5,
	0x29, 0x85, 0xc3, 0x3c, 0xce, 0xd0, 0x25, 0x3e, 0x09, 0x26, 0xbc, 0xd5, 0xec, 0x1e, 0xa0, 0x63,
	0xa4, 0x68, 0xa8, 0x0b, 0x47, 0x19, 0x2a, 0x15, 0xaf, 0x7b, 0xa8, 0x1f, 0xe9, 0x19, 0x8c, 0xf3,
	0x3a, 0x73, 0x0f, 0x7c, 0x12, 0x58, 0xdc, 0x48, 0x06, 0xe0, 0xcc, 0x51, 0xbf, 0x25, 0x1c, 0x4b,
	0x76, 0x0d, 0x60, 0xf4, 0xb3, 0xe2, 0xa8, 0xa4, 0x61, 0xd3, 0x44, 0xb9, 0xc4, 0x1f, 0x07, 0x63,
	0x6e, 0xa4, 0x49, 0x32, 0x47, 0xbd, 0xd0, 0x15, 0xc6, 0x19, 0xc7, 0x72, 0x6f, 0x92, 0x29, 0x9c,
	0x0e, 0x18, 0x25, 0xe9, 0x05, 0xd8, 0x15, 0xaa, 0x5a, 0xe8, 0x0e, 0xeb, 0xa6, 0xdb, 0x2f, 0x02,
	0x56, 0x9b, 0x99, 0x3e, 0x82, 0xb3, 0x88, 0x9b, 0xad, 0xbe, 0x0a, 0x07, 0xd5, 0xc3, 0x61, 0x6f,
	0xef, 0x72, 0x9f, 0x25, 0x45, 0xc3, 0x46, 0xf4, 0x01, 0xac, 0x36, 0x38, 0x3d, 0xff, 0xc3, 0xf4,
	0xc5, 0x76, 0xae, 0xfe, 0x76, 0x64, 0x23, 0xfa, 0x02, 0x93, 0x9f, 0xbc, 0x3b, 0xbf, 0x0f, 0xbb,
	0x7a, 0xde, 0x7f, 0x96, 0x79, 0xe5, 0x86, 0x3c, 0x39, 0xef, 0xf6, 0x76, 0x91, 0x1f, 0x76, 0xbb,
	0xc3, 0xbb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf1, 0xb7, 0x95, 0x81, 0xee, 0x01, 0x00, 0x00,
}
